version: '3.4'

services:
  SqlServerDb:
    container_name: mysqlserver
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=MyPass@word
      - MSSQL_USER=SAa
  
  api:
    container_name: myapplication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7107:80"

      
    depends_on:
      - SqlServerDb
    
  
  
